import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./utlis/provider/ReactQueryProvider";
import UserAuthContextProvider from "./context/UserAuthContextProvider";
import { ToastContainer } from "react-toastify";
import Providers from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserAuthContextProvider>
        <ReactQueryProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
                    <Providers/>

            <ToastContainer />

            {children}

          </body>
        </ReactQueryProvider>
      </UserAuthContextProvider>
    </html>
  );
}
